import {PcbBoardLayerMaterials, PcbBoardLayersMap} from "../bakedModels";
import {mmToMeters} from "../unitConversion";

import colors from "./Colors";

interface IStackupConfigDirectory {
    [category: string]: IStackupConfigMap;
}

interface IStackupConfigMap {
    [key: string]: IStackupConfig;
}

export interface IStackupConfig {
    key: string;
    label: string;
    layers: PcbBoardLayersMap;
}

export function getAllStackupConfigLabels() {
    const results: string[] = [];

    Object.values(stackups).forEach((stackupConfigs) => {
        Object.values(stackupConfigs).forEach((stackupConfig) => {
            results.push(stackupConfig.label);
        });
    });

    return results;
}

export function isCopperLayer(material: PcbBoardLayerMaterials | undefined) {
    if (material === "Copper" || material?.startsWith("CF-")) {
        return true;
    }

    return false;
}

export const staticLayoutLayers: PcbBoardLayersMap = {
    meta: {uid: "meta", type: "Metadata", order: -10, name: "Metadata", color: "#fff"},
    outline: {uid: "outline", type: "Metadata", order: -9, name: "Board Outline", color: "#FFEB3B"},
    holes: {uid: "holes", type: "Metadata", order: -8, name: "Drill Holes", color: "#7CB342"},
};

export const DEFAULT_FOOTPRINT_STACKUP_KEY = "footprint-2-layer";
const stackups: IStackupConfigDirectory = {
    standard: {
        "1": {
            // Total thickness 1.5604mm // Not an altium preset
            key: "standard-1-layer",
            label: "Standard 1 Layer",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4.0,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "Copper",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "FR-4",
                    thickness: mmToMeters(1.5),
                    dielectricMaterial: "FR-4",
                    dielectric: 4.29,
                },
            },
        },
        "2": {
            // Total thickness 1.6194mm // This is Altium 2 layers Preset
            key: "standard-2-layer",
            label: "Standard 2 Layer",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "Core-043",
                    thickness: mmToMeters(1.4986),
                    dielectricMaterial: "Core",
                    dielectric: 4.3,
                },
                "6": {
                    uid: "6",
                    name: "Bottom Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomCopper,
                    order: 6,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Bottom",
                },
                "7": {
                    uid: "7",
                    name: "Bottom Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderMask,
                    order: 7,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Bottom",
                },
                "8": {
                    uid: "8",
                    name: "Bottom Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderPaste,
                    order: 8,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Bottom",
                },
                "9": {
                    uid: "9",
                    name: "Bottom Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomOverlay,
                    order: 9,
                    type: "Overlay",
                    orientation: "Bottom",
                },
            },
        },
        "3": {
            // Total thickness 1.42016mm // This is Altium 4 layers Preset
            key: "standard-4-layer",
            label: "Standard 4 Layer",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "PP-017",
                    thickness: mmToMeters(0.12954),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "6": {
                    uid: "6",
                    name: "Dielectric 2",
                    order: 6,
                    type: "Dielectric",
                    material: "PP-017",
                    thickness: mmToMeters(0.12954),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "7": {
                    uid: "7",
                    name: "Mid-Layer 1",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer1,
                    order: 7,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "8": {
                    uid: "8",
                    name: "Dielectric 3",
                    order: 8,
                    type: "Dielectric",
                    material: "Core-039",
                    thickness: mmToMeters(0.7112),
                    dielectricMaterial: "Core",
                    dielectric: 4.8,
                },
                "9": {
                    uid: "9",
                    name: "Mid-Layer 2",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer2,
                    order: 9,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "10": {
                    uid: "10",
                    name: "Dielectric 4",
                    order: 10,
                    type: "Dielectric",
                    material: "PP-017",
                    thickness: mmToMeters(0.12954),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "11": {
                    uid: "11",
                    name: "Dielectric 5",
                    order: 11,
                    type: "Dielectric",
                    material: "PP-017",
                    thickness: mmToMeters(0.12954),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "12": {
                    uid: "12",
                    name: "Bottom Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomCopper,
                    order: 12,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Bottom",
                },
                "13": {
                    uid: "13",
                    name: "Bottom Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderMask,
                    order: 13,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Bottom",
                },
                "14": {
                    uid: "14",
                    name: "Bottom Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderPaste,
                    order: 14,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Bottom",
                },
                "15": {
                    uid: "15",
                    name: "Bottom Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomOverlay,
                    order: 15,
                    type: "Overlay",
                    orientation: "Bottom",
                },
            },
        },
        "4": {
            // Total thickness 1.60193 // This is Altium 6 layers Preset
            key: "standard-6-layer",
            label: "Standard 6 Layer",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "6": {
                    uid: "6",
                    name: "Dielectric 2",
                    order: 6,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "7": {
                    uid: "7",
                    name: "Mid-Layer 1",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer1,
                    order: 7,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "8": {
                    uid: "8",
                    name: "Dielectric 3",
                    order: 8,
                    type: "Dielectric",
                    material: "Core-035",
                    thickness: mmToMeters(0.4572),
                    dielectricMaterial: "Core",
                    dielectric: 4.7,
                },
                "9": {
                    uid: "9",
                    name: "Mid-Layer 2",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer2,
                    order: 9,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "10": {
                    uid: "10",
                    name: "Dielectric 4",
                    order: 10,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "11": {
                    uid: "11",
                    name: "Dielectric 5",
                    order: 11,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "12": {
                    uid: "12",
                    name: "Mid-Layer 3",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer3,
                    order: 12,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "13": {
                    uid: "13",
                    name: "Dielectric 6",
                    order: 13,
                    type: "Dielectric",
                    material: "Core-035",
                    thickness: mmToMeters(0.4572),
                    dielectricMaterial: "Core",
                    dielectric: 4.7,
                },
                "14": {
                    uid: "14",
                    name: "Mid-Layer 4",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer4,
                    order: 14,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "15": {
                    uid: "15",
                    name: "Dielectric 7",
                    order: 15,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "16": {
                    uid: "16",
                    name: "Dielectric 8",
                    order: 16,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "17": {
                    uid: "17",
                    name: "Bottom Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomCopper,
                    order: 17,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Bottom",
                },
                "18": {
                    uid: "18",
                    name: "Bottom Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderMask,
                    order: 18,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Bottom",
                },
                "19": {
                    uid: "19",
                    name: "Bottom Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderPaste,
                    order: 19,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Bottom",
                },
                "20": {
                    uid: "20",
                    name: "Bottom Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomOverlay,
                    order: 20,
                    type: "Overlay",
                    orientation: "Bottom",
                },
            },
        },
        "5": {
            // Total thickness 1.58557mm // This is Altium 6 layers Preset
            key: "standard-8-layer",
            label: "Standard 8 Layer",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "6": {
                    uid: "6",
                    name: "Dielectric 2",
                    order: 6,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "7": {
                    uid: "7",
                    name: "Mid-Layer 1",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer1,
                    order: 7,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "8": {
                    uid: "8",
                    name: "Dielectric 3",
                    order: 8,
                    type: "Dielectric",
                    material: "Core-027",
                    thickness: mmToMeters(0.2286),
                    dielectricMaterial: "Core",
                    dielectric: 4.5,
                },
                "9": {
                    uid: "9",
                    name: "Mid-Layer 2",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer2,
                    order: 9,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "10": {
                    uid: "10",
                    name: "Dielectric 4",
                    order: 10,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "11": {
                    uid: "11",
                    name: "Dielectric 5",
                    order: 11,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "12": {
                    uid: "12",
                    name: "Mid-Layer 3",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer3,
                    order: 12,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "13": {
                    uid: "13",
                    name: "Dielectric 6",
                    order: 13,
                    type: "Dielectric",
                    material: "Core-027",
                    thickness: mmToMeters(0.2286),
                    dielectricMaterial: "Core",
                    dielectric: 4.5,
                },
                "14": {
                    uid: "14",
                    name: "Mid-Layer 4",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer4,
                    order: 14,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "15": {
                    uid: "15",
                    name: "Dielectric 7",
                    order: 15,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "16": {
                    uid: "16",
                    name: "Dielectric 8",
                    order: 16,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "17": {
                    uid: "17",
                    name: "Mid-Layer 5",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer5,
                    order: 17,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "18": {
                    uid: "18",
                    name: "Dielectric 9",
                    order: 18,
                    type: "Dielectric",
                    material: "Core-027",
                    thickness: mmToMeters(0.2286),
                    dielectricMaterial: "Core",
                    dielectric: 4.5,
                },
                "19": {
                    uid: "19",
                    name: "Mid-Layer 6",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer6,
                    order: 19,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "20": {
                    uid: "20",
                    name: "Dielectric 10",
                    order: 20,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "21": {
                    uid: "21",
                    name: "Dielectric 11",
                    order: 21,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "22": {
                    uid: "22",
                    name: "Bottom Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomCopper,
                    order: 22,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Bottom",
                },
                "23": {
                    uid: "23",
                    name: "Bottom Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderMask,
                    order: 23,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Bottom",
                },
                "24": {
                    uid: "24",
                    name: "Bottom Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderPaste,
                    order: 24,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Bottom",
                },
                "25": {
                    uid: "25",
                    name: "Bottom Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomOverlay,
                    order: 25,
                    type: "Overlay",
                    orientation: "Bottom",
                },
            },
        },
        "6": {
            // Total thickness 1.62001mm // This is Altium 10 layers Preset
            key: "standard-10-layer",
            label: "Standard 10 Layer",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "6": {
                    uid: "6",
                    name: "Dielectric 2",
                    order: 6,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "7": {
                    uid: "7",
                    name: "Mid-Layer 1",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer1,
                    order: 7,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "8": {
                    uid: "8",
                    name: "Dielectric 3",
                    order: 8,
                    type: "Dielectric",
                    material: "Core-016",
                    thickness: mmToMeters(0.127),
                    dielectricMaterial: "Core",
                    dielectric: 4.3,
                },
                "9": {
                    uid: "9",
                    name: "Mid-Layer 2",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer2,
                    order: 9,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "10": {
                    uid: "10",
                    name: "Dielectric 4",
                    order: 10,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "11": {
                    uid: "11",
                    name: "Dielectric 5",
                    order: 11,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "12": {
                    uid: "12",
                    name: "Mid-Layer 3",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer3,
                    order: 12,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "13": {
                    uid: "13",
                    name: "Dielectric 6",
                    order: 13,
                    type: "Dielectric",
                    material: "Core-016",
                    thickness: mmToMeters(0.127),
                    dielectricMaterial: "Core",
                    dielectric: 4.3,
                },
                "14": {
                    uid: "14",
                    name: "Mid-Layer 4",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer4,
                    order: 14,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "15": {
                    uid: "15",
                    name: "Dielectric 7",
                    order: 15,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "16": {
                    uid: "16",
                    name: "Dielectric 8",
                    order: 16,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "17": {
                    uid: "17",
                    name: "Mid-Layer 5",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer5,
                    order: 17,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "18": {
                    uid: "18",
                    name: "Dielectric 9",
                    order: 18,
                    type: "Dielectric",
                    material: "Core-016",
                    thickness: mmToMeters(0.127),
                    dielectricMaterial: "Core",
                    dielectric: 4.3,
                },
                "19": {
                    uid: "19",
                    name: "Mid-Layer 6",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer6,
                    order: 19,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "20": {
                    uid: "20",
                    name: "Dielectric 10",
                    order: 20,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "21": {
                    uid: "21",
                    name: "Dielectric 11",
                    order: 21,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "22": {
                    uid: "22",
                    name: "Mid-Layer 7",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer7,
                    order: 22,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "23": {
                    uid: "23",
                    name: "Dielectric 12",
                    order: 23,
                    type: "Dielectric",
                    material: "Core-016",
                    thickness: mmToMeters(0.127),
                    dielectricMaterial: "Core",
                    dielectric: 4.3,
                },
                "24": {
                    uid: "24",
                    name: "Mid-Layer 8",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer8,
                    order: 24,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "25": {
                    uid: "25",
                    name: "Dielectric 13",
                    order: 25,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "26": {
                    uid: "26",
                    name: "Dielectric 14",
                    order: 26,
                    type: "Dielectric",
                    material: "PP-006",
                    thickness: mmToMeters(0.07112),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.1,
                },
                "27": {
                    uid: "27",
                    name: "Bottom Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomCopper,
                    order: 27,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Bottom",
                },
                "28": {
                    uid: "28",
                    name: "Bottom Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderMask,
                    order: 28,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Bottom",
                },
                "29": {
                    uid: "29",
                    name: "Bottom Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderPaste,
                    order: 29,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Bottom",
                },
                "30": {
                    uid: "30",
                    name: "Bottom Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomOverlay,
                    order: 30,
                    type: "Overlay",
                    orientation: "Bottom",
                },
            },
        },
        "7": {
            // Total thickness 1.57825mm // This is Altium 12 layers Preset
            key: "standard-12-layer",
            label: "Standard 12 Layer",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "PP-013",
                    thickness: mmToMeters(0.09652),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "6": {
                    uid: "6",
                    name: "Mid-Layer 1",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer1,
                    order: 6,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "7": {
                    uid: "7",
                    name: "Dielectric 2",
                    order: 7,
                    type: "Dielectric",
                    material: "Core-011",
                    thickness: mmToMeters(0.1016),
                    dielectricMaterial: "Core",
                    dielectric: 4.4,
                },
                "8": {
                    uid: "8",
                    name: "Mid-Layer 2",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer2,
                    order: 8,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "9": {
                    uid: "9",
                    name: "Dielectric 3",
                    order: 9,
                    type: "Dielectric",
                    material: "PP-013",
                    thickness: mmToMeters(0.09652),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "10": {
                    uid: "10",
                    name: "Mid-Layer 3",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer3,
                    order: 10,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "11": {
                    uid: "11",
                    name: "Dielectric 4",
                    order: 11,
                    type: "Dielectric",
                    material: "Core-011",
                    thickness: mmToMeters(0.1016),
                    dielectricMaterial: "Core",
                    dielectric: 4.4,
                },
                "12": {
                    uid: "12",
                    name: "Mid-Layer 4",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer4,
                    order: 12,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "13": {
                    uid: "13",
                    name: "Dielectric 5",
                    order: 13,
                    type: "Dielectric",
                    material: "PP-014",
                    thickness: mmToMeters(0.10668),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.2,
                },
                "14": {
                    uid: "14",
                    name: "Mid-Layer 5",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer5,
                    order: 14,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "15": {
                    uid: "15",
                    name: "Dielectric 6",
                    order: 15,
                    type: "Dielectric",
                    material: "Core-011",
                    thickness: mmToMeters(0.1016),
                    dielectricMaterial: "Core",
                    dielectric: 4.4,
                },
                "16": {
                    uid: "16",
                    name: "Mid-Layer 6",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer6,
                    order: 16,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "17": {
                    uid: "17",
                    name: "Dielectric 7",
                    order: 17,
                    type: "Dielectric",
                    material: "PP-014",
                    thickness: mmToMeters(0.10668),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.2,
                },
                "18": {
                    uid: "18",
                    name: "Mid-Layer 7",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer7,
                    order: 18,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "19": {
                    uid: "19",
                    name: "Dielectric 8",
                    order: 19,
                    type: "Dielectric",
                    material: "Core-011",
                    thickness: mmToMeters(0.1016),
                    dielectricMaterial: "Core",
                    dielectric: 4.4,
                },
                "20": {
                    uid: "20",
                    name: "Mid-Layer 8",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer8,
                    order: 20,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "21": {
                    uid: "21",
                    name: "Dielectric 9",
                    order: 21,
                    type: "Dielectric",
                    material: "PP-013",
                    thickness: mmToMeters(0.09652),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "22": {
                    uid: "22",
                    name: "Mid-Layer 9",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer9,
                    order: 22,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "23": {
                    uid: "23",
                    name: "Dielectric 10",
                    order: 23,
                    type: "Dielectric",
                    material: "Core-011",
                    thickness: mmToMeters(0.1016),
                    dielectricMaterial: "Core",
                    dielectric: 4.4,
                },
                "24": {
                    uid: "24",
                    name: "Mid-Layer 10",
                    color: colors.canvas.pcb.layout.stackupLayerColors.midLayer10,
                    order: 24,
                    type: "Power Plane",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                },
                "25": {
                    uid: "25",
                    name: "Dielectric 11",
                    order: 25,
                    type: "Dielectric",
                    material: "PP-013",
                    thickness: mmToMeters(0.09652),
                    dielectricMaterial: "Prepreg",
                    dielectric: 4.3,
                },
                "26": {
                    uid: "26",
                    name: "Bottom Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomCopper,
                    order: 26,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Bottom",
                },
                "27": {
                    uid: "27",
                    name: "Bottom Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderMask,
                    order: 27,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Bottom",
                },
                "28": {
                    uid: "28",
                    name: "Bottom Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderPaste,
                    order: 28,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Bottom",
                },
                "29": {
                    uid: "29",
                    name: "Bottom Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomOverlay,
                    order: 29,
                    type: "Overlay",
                    orientation: "Bottom",
                },
            },
        },
        "8": {
            // Total thickness 1.6194mm // This is will be our default footprint stackup
            key: DEFAULT_FOOTPRINT_STACKUP_KEY,
            label: "Footprint",
            layers: {
                ...staticLayoutLayers,
                "1": {
                    uid: "1",
                    name: "Top Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topOverlay,
                    order: 1,
                    type: "Overlay",
                    orientation: "Top",
                },
                "2": {
                    uid: "2",
                    name: "Top Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderPaste,
                    order: 2,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Top",
                },
                "3": {
                    uid: "3",
                    name: "Top Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topSolderMask,
                    order: 3,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Top",
                },
                "4": {
                    uid: "4",
                    name: "Top Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.topCopper,
                    order: 4,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Top",
                },
                "5": {
                    uid: "5",
                    name: "Dielectric 1",
                    order: 5,
                    type: "Dielectric",
                    material: "Core-043",
                    thickness: mmToMeters(1.4986),
                    dielectricMaterial: "Core",
                    dielectric: 4.3,
                },
                "6": {
                    uid: "6",
                    name: "Bottom Copper",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomCopper,
                    order: 6,
                    type: "Signal",
                    material: "CF-004",
                    thickness: mmToMeters(0.035),
                    orientation: "Bottom",
                },
                "7": {
                    uid: "7",
                    name: "Bottom Solder Mask",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderMask,
                    order: 7,
                    type: "Solder Mask",
                    material: "Solder Mask",
                    thickness: mmToMeters(0.0254),
                    dielectricMaterial: "Epoxy Liquid",
                    dielectric: 4,
                    orientation: "Bottom",
                },
                "8": {
                    uid: "8",
                    name: "Bottom Solder Paste",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomSolderPaste,
                    order: 8,
                    type: "Solder Paste",
                    material: "PbSn",
                    thickness: mmToMeters(0.01),
                    orientation: "Bottom",
                },
                "9": {
                    uid: "9",
                    name: "Bottom Overlay",
                    color: colors.canvas.pcb.layout.stackupLayerColors.bottomOverlay,
                    order: 9,
                    type: "Overlay",
                    orientation: "Bottom",
                },
            },
        },
    },
};

export default stackups;
