import {PropertyValueTypes} from "../SharedDataModels";

export interface IDefaultProperty {
    key: string;
    label: string;
    unit?: string;
    type?: string;
    valueType?: PropertyValueTypes;
    exclude_from_bom?: boolean;
    auto_complete_options?: string[];
}

export const defaultPinType = "Unspecified";

export enum DefaultPropertyTypes {
    value = "value",
    symbolPinPosition = "symbol_pin_position",
    pinNumber = "pinNumber",
}

const strings = {
    app: {
        name: "Flux",
        tag_line: "Build circuits. Write code.",
        description:
            "We help hardware teams build better products through modern collaboration, live simulation, and a community library of parts.",
        description2:
            "Flux is where engineers shape the future of hardware, together. Contribute to the open source community, manage your projects, review schematics like a pro, track issues and features, power your workflows, and secure work before you commit it.",
        flux_twitter_handle: "buildwithflux",
        network_error_prompt:
            "Flux is having trouble connecting to the internet and some of your last edits weren't saved yet. Flux will attempt to reconnect in",
    },
    signup: {
        title: "Create Account",
        sub_title: "Create a free account to start building hardware together with anyone from anywhere.",
    },
    validation_message: {
        required: "Required",
    },
    inspector: {
        document: {
            info_section: {
                title: "About",
                description: "Description",
                descriptionPlaceholder: "Description",
                created: "Created",
                lastUpdated: "Last updated by ",
                forkOf: "Forked from",
                copyOf: "Cloned from",
                contributors: "Contributor(s)",
            },
            simulator_section: {
                title: "Simulation",
            },
            properties_section: {
                title: "Properties",
            },
            pcb_layout_rules_section: {
                title: "Layout Rules",
            },
        },
        action_panel: {
            rotate: "Rotate Selected Element",
            flip: "Flip Selected Element",
            convert: "Convert Selected Element to Part",
            edit: "Edit Selected Part",
            delete: "Delete Selected Element",
        },
        empty_state: {
            content: "Select an element on the canvas to activate this panel.",
        },
        layout_section: {
            title: "Layout",
            x_schematic_position_label: "X",
            y_schematic_position_label: "Y",
            x_pcb_position_label: "X mm",
            y_pcb_position_label: "Y mm",
        },
        properties_section: {
            title: "Properties",
            defaultProperties: {
                symbol_pin_position: {
                    key: "symbol_pin_position",
                    label: "Symbol Pin Position",
                    valueType: "vector2",
                    type: DefaultPropertyTypes.symbolPinPosition,
                    exclude_from_bom: true,
                } as IDefaultProperty,
                pin_number: {
                    key: "pin_number",
                    label: "Pin Number",
                    type: DefaultPropertyTypes.pinNumber,
                    exclude_from_bom: true,
                } as IDefaultProperty,
                part_type: {
                    key: "part_type",
                    label: "Part Type",
                    auto_complete_options: [
                        "Resistor",
                        "Polarized Capacitor",
                        "Non-Polarized Capacitor",
                        "LED",
                        "Transistor",
                        "Inductor",
                        "Integrated Circuit",
                        "Operational Amplifier (OP-AMP)",
                        "Diode",
                        "Oscillator",
                        "Power Source",
                        "Display Device",
                        "Relay",
                        "Microcontroller",
                        "Switch",
                        "Antenna",
                        "Memristor",
                        "Protection",
                        "Terminal",
                        "Ground",
                    ],
                } as IDefaultProperty,
                terminal_type: {
                    key: "terminal_type",
                    label: "Terminal Type",
                },
                package_case_code: {
                    key: "package_case_code",
                    label: "Package or Case Code",
                    auto_complete_options: [
                        "SOT-23",
                        "SOT-23-5",
                        "SOT-23-6",
                        "SOT-23-8",
                        "SOT-223",
                        "SOT-323",
                        "SOT-363",
                        "SOT-416",
                        "SOT-666",
                        "SOT-723",
                        "TSOT-23-6",
                        "TO-263",
                        "4-SMD",
                        "4-UDFN",
                        "4-SO",
                        "4-DIP",
                        "5-TSSOP",
                        "6-PDIP",
                        "6-PLCC",
                        "6-DFN",
                        "6-DSBGA",
                        "6-TDFN",
                        "6-TSOP",
                        "6-TSSOP",
                        "6-WDFN",
                        "6-WSON",
                        "6-SO",
                        "8-DFN",
                        "8-DSBGA",
                        "8-LGA",
                        "8-MSOP",
                        "8-SIP",
                        "8-PDIP",
                        "8-DIP",
                        "8-SOIC",
                        "8-SO",
                        "8-SSOP",
                        "8-TDFN",
                        "8-TSSOP",
                        "8-UDFN",
                        "8-VDFN",
                        "8-WDFN",
                        "8-WSON",
                        "8-VSSOP",
                        "9-DSBGA",
                        "9-SIP",
                        "10-DFN",
                        "10-UDFN",
                        "10-HVSSOP",
                        "10-VSSOP",
                        "10-MSOP",
                        "10-TDFN",
                        "10-VSON",
                        "10-USON",
                        "10-WSON",
                        "12-DFN",
                        "12-TDFN",
                        "12-WDFN",
                        "12-LGA",
                        "12-DSBGA",
                        "12-MSOP",
                        "12-QFN",
                        "14-SOIC",
                        "14-DIP",
                        "14-LGA",
                        "14-WQFN",
                        "14-WSON",
                        "14-TSSOP",
                        "14-HTSSOP",
                        "15-WLP",
                        "16-DIP",
                        "16-QFN",
                        "16-QSOP",
                        "16-MSOP",
                        "16-SOIC",
                        "16-LGA",
                        "16-MLPQ",
                        "16-DFN",
                        "16-SMDIP",
                        "16-WSON",
                        "16-BGA",
                        "16-SSOP",
                        "16-SOP",
                        "16-TSSOP",
                        "16-VQFN",
                        "16-UQFN",
                        "16-WLP",
                        "16-WQFN",
                        "18-SOIC",
                        "18-DIP",
                        "18-DFN",
                        "18-SOP",
                        "18-SSOP",
                        "20-SOIC",
                        "20-USON",
                        "20-SO",
                        "20-DIP",
                        "20-QFN",
                        "20-WQFN",
                        "20-UQFN",
                        "20-MLF",
                        "20-MLPQ",
                        "20-SSOP",
                        "20-TQFN",
                        "20-TSSOP",
                        "20-ETSSOP",
                        "20-HTSSOP",
                        "20-VQFN",
                        "22-DFN",
                        "22-DIP",
                        "24-QFN",
                        "24-DIP",
                        "24-DFN",
                        "24-LGA",
                        "24-QSOP",
                        "24-SOIC",
                        "24-SSOP",
                        "24-TQFN",
                        "24-TSSOP",
                        "24-VQFN",
                        "24-WQFN",
                        "24-HTSSOP",
                        "25-BGA",
                        "28-DIP",
                        "28-QFN",
                        "28-UQFN",
                        "28-SSOP",
                        "28-SOIC",
                        "28-HTSSOP",
                        "28-TSSOP",
                        "28-LGA",
                        "28-VQFN",
                        "30-TSSOP",
                        "32-QFN",
                        "32-DIP",
                        "32-WQFN",
                        "32-LQFP",
                        "32-TQFP",
                        "32-HTSSOP",
                        "32-TSSOP",
                        "32-SSOP",
                        "32-VQFN",
                        "36-BGA",
                        "36-QFN",
                        "36-SOJ",
                        "38-TSSOP",
                        "38-HTSSOP",
                        "38-QFN",
                        "40-DIP",
                        "40-QFN",
                        "40-UQFN",
                        "40-VSOP",
                        "42-DIP",
                        "42-QFN",
                        "44-LQFP",
                        "44-PQFP",
                        "44-QFN",
                        "44-TQFP",
                        "44-SSOP",
                        "44-TSSOP",
                        "48-TSSOP",
                        "48-SSOP",
                        "48-BGA",
                        "48-DIP",
                        "48-QFN",
                        "48-UQFN",
                        "48-LQFP",
                        "48-TQFP",
                        "49-DSBGA",
                        "49-VFBGA",
                        "50-TSSOP",
                        "52-LQFP",
                        "52-TQFP",
                        "52-QFN",
                        "52-TSSOP",
                        "56-QFN",
                        "56-HTSSOP",
                        "56-SSOP",
                        "56-TSSOP",
                        "56-VSO",
                        "64-BGA",
                        "64-DSBGA",
                        "64-TFBGA",
                        "64-UFBGA",
                        "64-QFN",
                        "64-LQFP",
                        "64-TQFP",
                        "64-HTQFP",
                        "64-TSSOP",
                        "68-BGA",
                        "68-QFN",
                        "73-VFQFN",
                        "76-QFN",
                        "78-FBGA",
                        "80-LQFP",
                        "80-PQFP",
                        "80-TQFP",
                        "80-VQFP",
                        "80-TSSOP",
                        "81-BGA",
                        "81-UCBGA",
                        "90-BGA",
                        "96-BGA",
                        "100-TFBGA",
                        "100-LQFP",
                        "100-PQFP",
                        "100-TQFP",
                        "100-VQFP",
                        "R_0201_0603Metric",
                        "R_0402_1005Metric",
                        "R_0603_1608Metric",
                        "R_0805_2012Metric",
                        "R_1206_3216Metric",
                        "R_1210_3225Metric",
                        "R_1806_4516Metric",
                        "R_1812_4532Metric",
                        "R_2010_5025Metric",
                        "R_2512_6332Metric",
                        "R_POT_PV36P",
                        "R_POT_PV36W",
                        "R_POT_PV36X",
                        "R_POT_PV36Y",
                        "R_POT_PV36Z",
                        "R_AXIAL_724W46L381D178B",
                        "R_AXIAL_1176W63L850D250B",
                        "R_AXIAL_Vertical",
                        "C_0402_1005Metric",
                        "C_0603_1608Metric",
                        "C_0805_2012Metric",
                        "C_1206_3216Metric",
                        "C_1210_3225Metric",
                        "C_1812_4532Metric",
                        "C_1825_4564Metric",
                        "CP_3216-18_Kemet-A",
                        "CP_3528-21_Kemet-B",
                        "CP_6032-28_Kemet-C",
                        "CP_7343-31_Kemet-D",
                        "CPOL_830X1050Metric",
                        "CPOL_1030X1050Metric",
                        "CPOL_1905X1660Metric",
                        "D_0603_1608Metric",
                        "D_0805_2012Metric",
                        "D_1206_3216Metric",
                        "D_2010_5025Metric",
                        "D_2114_3652Metric",
                        "D_3220_8050Metric",
                        "D_MELF",
                        "D_MicroMELF",
                        "D_MiniMELF",
                        "D_PowerDI-123",
                        "D_SC-80",
                        "D_SMA",
                        "D_SMB",
                        "D_SMC",
                        "D_SOD-110",
                        "D_SOD-123",
                        "D_SOD-123F",
                        "D_SOD-323",
                        "D_SOD-323F",
                        "D_SOD-523",
                        "D_TUMD2",
                        "L_0201_0603Metric",
                        "L_0402_1005Metric",
                        "L_0603_1608Metric",
                        "L_0805_2012Metric",
                        "L_1206_3216Metric",
                        "L_1210_3225Metric",
                        "L_1806_4516Metric",
                        "L_1812_4532Metric",
                        "L_2010_5025Metric",
                        "L_2512_6332Metric",
                        "MODULE_WEMOS_D1_MINI",
                        "DISP_7SEG_10DIP",
                        "male_ufl_connector",
                        "usb_micro_female",
                        "usb_mini_female",
                        "usb_a_type_female",
                        "usb_a_type_female_double_stack",
                    ],
                } as IDefaultProperty,
                terminal_order: {key: "terminal_order", label: "Terminal Order", exclude_from_bom: true},
                pin_type: {
                    key: "pin_type",
                    label: "Pin Type",
                    auto_complete_options: [
                        "Passive",
                        "Power In",
                        "Power Out",
                        "Not Connected",
                        defaultPinType,
                        "Signal",
                        "Input",
                        "Output",
                        "Bi-Directional",
                        "Tri-State",
                        "Open Collector",
                        "Open Emitter",
                    ],
                } as IDefaultProperty,
                designator_prefix: {
                    key: "designator_prefix",
                    label: "Designator Prefix",
                    exclude_from_bom: true,
                } as IDefaultProperty,
                voltage: {
                    key: "voltage",
                    label: "Voltage",
                    unit: "V",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                resistance: {
                    key: "resistance",
                    label: "Resistance",
                    unit: "Ω",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                tolerance: {
                    key: "tolerance",
                    label: "Tolerance",
                    unit: "%",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                capacitance: {
                    key: "capacitance",
                    label: "Capacitance",
                    unit: "F",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                power: {
                    key: "power",
                    label: "Power",
                    unit: "W",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                current: {
                    key: "current",
                    label: "Current",
                    unit: "A",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                frequency: {
                    key: "frequency",
                    label: "Frequency",
                    unit: "Hz",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                inductance: {
                    key: "inductance",
                    label: "Inductance",
                    unit: "H",
                    type: DefaultPropertyTypes.value,
                } as IDefaultProperty,
                single_unit_price: {key: "single_unit_price", label: "Price", unit: "$"},
                purchase_url: {key: "purchase_url", label: "Purchase Url"},
                product_info_url: {key: "product_info_url", label: "Product Info Url"},
                datasheet_url: {key: "datasheet_url", label: "Datasheet URL"},
                mpn: {key: "mpn", label: "Manufacturer Part Number"},
                substitute_mpn: {key: "substitute_mpn", label: "Substitute Manufacturer Part Number"},
                kicad_library_reference: {key: "kicad_library_reference", label: "KiCAD Library Reference"},
                kicad_component_orientation_offset: {
                    key: "kicad_component_orientation_offset",
                    label: "KiCAD Orientation Offset",
                    unit: "°",
                    exclude_from_bom: true,
                },
                manufacturer_name: {
                    key: "manufacturer_name",
                    label: "Manufacturer Name",
                    // For complete lists from distributors, see mouserManufacturerList, digikeyManufacturerList, lcscManufacturerList.
                    // When adding a new option, avoid common suffixes like Inc, Corp, or words like Electronics or Devices.
                    auto_complete_options: [
                        "Intel Corporation",
                        "Samsung",
                        "Toshiba",
                        "Texas Instruments",
                        "Analog Devices",
                        "Renesas",
                        "Hynix",
                        "STMicroelectronics",
                        "Micron",
                        "Microchip",
                        "Qualcomm",
                        "Broadcom",
                        "Elpida Memory",
                        "Advanced Micro Devices",
                        "Infineon",
                        "Sony",
                        "Panasonic",
                        "Freescale",
                        "NXP",
                        "Marvell",
                        "MediaTek",
                        "NVIDIA",
                        "Seed Technology",
                    ],
                },
                exclude_from_bom: {key: "exclude_from_bom", label: "Exclude from BOM", exclude_from_bom: true},
                exclude_from_pcb: {key: "exclude_from_pcb", label: "Exclude from PCB", exclude_from_pcb: true},
            },
        },
        pcb_layout_rules_section: {
            title: "Layout Rules",
        },
        info_section: {
            title: "Entity Info",
        },
        part_section: {
            title: "About",
            name_input: "Part Name",
            description_input: "Part Description",
            version_input: "Part Version",
            created_at_input: "Part Created at",
        },
        pcb_layout_node_section: {
            title: "About",
        },
        simulation_panel: {
            title: "Simulation",
        },
        controls_panel: {
            title: "Controls",
            default_control_name: "New control",
            default_position_name: "New position",
        },
        controls_simulation_panel: {
            title: "Controls",
        },
        position_on_symbol: {
            title: "Position on Symbol",
        },
        assets: {
            title: "Assets",
            symbol: "Symbol",
            thumbnail: "Thumbnail",
        },
    },
    parts_browser: {
        empty_state: {
            content: "Sorry we couldn’t find what you were searching for. Would you like to add this part?",
            create_part_content: "Add new part",
        },
    },
    editor: {
        zoom_controls: {
            zoom_in: "Zoom In",
            zoom_out: "Zoom Out",
            zoom_to_fit: "Zoom To Fit",
        },
        mode_controls: {
            two_d: "2D",
            two_d_label: "Switch to 2D",
            three_d: "3D",
            three_d_label: "Switch to 3D",
            show_grid: "Grid",
            show_grid_label: "Grid",
        },
        nav_bar: {
            document_name_editor: {
                placeholder_content: "Enter Project Name",
            },
        },
        code: {
            default_welcome_message:
                "// Howdy 👋.\n" +
                "// \n" +
                "// If you are new to writing code in Flux make sure to check out our get started docs: https://docs.flux.ai/write-code \n" +
                "// \n" +
                "// We also have a Flux Slack Community in case you need help: https://join.slack.com/t/fluxcommunity/shared_invite/zt-p48n941f-wzQ06kGmuFJ2HXnGYT1JkA \n" +
                "// \n" +
                "// To infinity and beyond 🚀 \n",
        },
    },
    hotkey_viewer: {
        title: "Keyboard Shortcuts",
    },
    share_sheet: {
        share_button_label: "Share",
        share_button_tooltip_content: {
            current_user: {
                off: "Private to only me.",
                edit: "You can edit.",
                view: "You can view.",
                comment: "You can comment.",
            },
            anyone: {
                off: "Private to only me.",
                edit: "Anyone can edit.",
                view: "Anyone can view.",
                comment: "Anyone can comment.",
            },
        },
        title: "Share with others",
        done_btn_label: "Done",
        roles: {
            off: "OFF - Only you can edit",
            edit: "Anyone can edit",
            view: "Anyone can view",
            comment: "Anyone can comment",
        },
        permission_select_input_label: "Permissions",
        copy_paste_tooltip: "Link copied to clipboard",
        copy_paste_embed_tooltip: "Embedded snipped copied to clipboard",
        copy_paste_button_label: "Copy Link",
        copy_paste_embed_snipped_button_label: "Copy Embed",
        advanced_button_label: "Advanced",
        advanced_roles: {
            edit: "Can edit",
            view: "Can view",
            comment: "Can comment",
        },
        advanced_title: "Who has access",
        advanced_add_btn: "Add",
        advanced_user_input_placeholder: "Enter user names",
        advanced_user_input_label: "Invite People",
    },
    profile: {
        inputQueryPlaceholder: "Find by name, description, ...",
        confirmDeletePrompt: "Are you sure you want to permanently delete ",
        confirmArchivePrompt: "Would you like to archive ",
        confirmArchiveContext: "You'll be able to access it later by opening your archive from the main menu.",
    },
    part_import_dialog: {
        title: "Import Parts",
        close_btn_label: "Close",
    },
    semi_conductor_manufacturers: [
        {
            name: "Texas Instruments Inc.",
            match: ["Texas Instruments", "TI"],
        },
        {
            name: "Seeed Technology Co",
            match: ["Seed"],
        },
        {
            name: "Analog Devices, Inc.",
            match: ["Analog Devices", "Linear Technology", "Linear Technology Corporation"],
        },
        {
            name: "Intel Corp",
            match: ["Intel"],
        },
        {
            name: "NVIDIA Corp",
            match: ["NVIDIA"],
        },
        {
            name: "Micron Technology, Inc.",
            match: ["Micron"],
        },
        {
            name: "Microchip Technology Inc.",
            match: ["Microchip"],
        },
        {
            name: "Skyworks Solutions, Inc.",
            match: ["Skyworks"],
        },
        {
            name: "Maxim Integrated Products, Inc.",
            match: ["Maxim"],
        },
        {
            name: "Xilinx, Inc.",
            match: ["Xilinx"],
        },
        {
            name: "Advanced Micro Devices, Inc.",
            match: ["AMD", "Advanced Micro Devices"],
        },
        {
            name: "Taiwan Semiconductor Manufacturing Co. Ltd.",
            match: ["Taiwan Semiconductor", "TSM"],
        },
        {
            name: "Qualcomm Inc.",
            match: ["Qualcomm", "QCOM"],
        },
        {
            name: "Broadcom Inc.",
            match: ["Broadcom", "AVGO"],
        },
        {
            name: "ASE Technology Holding Co. Ltd. (ASX)",
            match: ["ASE", "ASX"],
        },
        {
            name: "STMicroelectronics NV",
            match: ["STMicroelectronics", "STM"],
        },
        {
            name: "NXP Semiconductors NV",
            match: ["NXP", "NXPI"],
        },
        {
            name: "Samsung Electronics Co., Ltd.",
            match: ["Samsung"],
        },
        {
            name: "Toshiba Corp",
            match: ["Toshiba"],
        },
        {
            name: "MediaTek Inc.",
            match: ["MediaTek"],
        },
        {
            name: "Infineon Technologies AG",
            match: ["Infineon"],
        },
        {
            name: "Sony Corp",
            match: ["Sony"],
        },
        {
            name: "Arm Ltd.",
            match: ["Arm"],
        },
        {
            name: "ON Semiconductor",
            match: ["ON Semiconductor"],
        },
        {
            name: "United Microelectronics Corp",
            match: ["UMC"],
        },
        {
            name: "Fujitsu Ltd.",
            match: ["Fujitsu"],
        },
        {
            name: "Hitachi Ltd.",
            match: ["Hitachi"],
        },
        {
            name: "Panasonic Corp.",
            match: ["Panasonic"],
        },
    ],
    randomNamesDictionaries: {
        backToTheFuture: [
            "Heavy",
            "Jigowatt",
            "Pepsi free",
            "Slacker",
            "Daddy O",
            "Dreamboat",
            "Biff",
            "McFly",
            "Emmett",
            "Goldie Willson",
            "Strickland",
            "Clocktower Lady",
        ],
        mandalorian: [
            "Din Djarin",
            "Grogu",
            "Greef Karga",
            "The Client",
            "Dr. Pershing",
            "Kuiil",
            "IG-11",
            "Cara Dune",
            "Moff Gideon",
            "The Armorer",
            "Peli Motto",
            "Frog Lady",
            "Toro Calican",
            "Fennec Shand",
            "Ranzar Malk",
            "Mayfeld",
            "Xi'an",
            "Burg",
            "Q9-0",
            "Qin",
            "Gor Koresh",
            "Cobb Vanth",
            "Koska Reeves",
            "Bo-Katan Kryze",
            "Axe Woves",
            "Mythrol",
            "Lang",
            "Ahsoka Tano",
            "Morgan Elsbeth",
            "Omera",
            "Winta",
            "Caben",
            "Stoke",
            "Riot Mar",
            "Davan",
            "Trapper Wolf",
            "Jib Dodger",
            "Sash Ketter",
            "Carson Teva",
            "Governor Wing",
        ],
        dune: [
            "Arkie",
            "Alia Atreides",
            "Ghanima Atreides",
            "Ikonicre Atreides",
            "Lady Jessica",
            "Duke Leto",
            "Abulurd Harkonnen",
            "Baron Vladimir Harkonnen",
            "Anirul",
            "Norma Cenva",
            "Edric",
        ],
    },
    bannedAdjectives: ["sexual", "drunk", "religious", "brown"],
};

export default strings;
